version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        path: /opt/app
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081